### ISSUE TITLE
Amazing, but confused.

### ISSUE THREAD

**Issue by mirror-master** [eouia/MMM-Hotword#8] opened 2018-09-25 09:00 UTC
First let me say, thank you for your hard word.  But I cant get this to work with AssistantMk2 for the life of me.  
I cant seem to get it working, i have My AssistandMk2 working.
but i honestly cant figure out how to add it to my config to work as a wake word.  Im currently leaving as default.  Tried several combinations but im not at the level you guys are at.  Any help would be a blessing.

Cheers

**Comment by Donlar714** [comment] 2018-09-26 01:04
I followed all steps to this point. All has worked pout well, but after adding the Hotword, notification trigger and mk2 assistant to the config.json i get a black blank screen and no working functions. If I remove the modules form th config file i am able toview the basic magic mirror clock, calendar, weather, ect.. 
What can i do to remedy this?

**Comment by eouia** [comment] 2018-09-26 06:58
Give me more detailed error logs(backend and frontend both). You can get those by execution `npm start dev`.

**Comment by mirror-master** [comment] 2018-09-29 02:48
@eouia if i try that config it won't work.  My mkassistant has its details for the Mic, if I use default values it won't work. I do have notification as well. Tried the suggested combo.  Trying to doggie put how to use the three plus my mkassistant config. thank you for your time

**Comment by mirror-master** [comment] 2018-09-29 02:57
@eouia im thinking I can't use that code because I don't have a asoundrc for choosing defaults for me... Smh

**Comment by eouia** [comment] 2018-09-29 14:50
You can contact me with Telegram. My Telegram id is “@eouia”

**Comment by eouia** [comment] 2018-10-16 07:06
Only "smart mirror" couldn't be recognized? How about other hotwords - "jarvis" or "snowboy"?

**Comment by juanmam5** [comment] 2018-10-16 09:41
I've tried smart mirror and snowboy and it's the same. Even worst with jarvis but it could be due to my spanish pronunciation of the word jarvis. I have the magic mirror configure in spanish, I don't know if it could affect to the recognition of the english words but when it recognize the hotword, then it gets all I say perfectly, spanish or english, doesn't matter.

**Comment by eouia** [comment] 2018-10-16 11:15
Hotword itself is not the language. it is just some pattern of voice. Of course, it would be fit for English accent and pronunciation, but I think some vocal exercise could be help.
I just have a curious. none of all trial was failed to be recognized? or sometime success? If sometime you can activate, I can say just more vocal training is needed.
But none of all trials was failed, there could be other reasons.
Anyway, you can make your own private voice pattern model(.pmdl) in http://snowboy.kitt.ai site.

**Comment by juanmam5** [comment] 2018-10-18 08:50
I have already changed the power for the right one but nothing has change. Voice of the Google Assistant is still choppy and it only recognize the hotword sometimes. Can I send you a video so you can see what's happening?

**Comment by eouia** [comment] 2018-10-18 09:05
Well, I know that issue already, but I cannot reproduce it by myself. So, video will not help. 
Anyway, I think that is not your fault.
RPI is not so powerful to do hard work. 
It might be caused by many modules(especially consuming system resources like timer or interruptor) or many background process (your other background programs besides MM)
In those case, nothing remains to solve.
You'd said there was no problem to playing sounds(mp3) out of MM, so it's not problem of HW or system.
When only in MM you'd met this sound problem, it might mean your RPI & MM has not enough power(not mean electricity) to work this module seamlessly.
(With similar reasons, I'd abandoned RPI - currently My major SBC is ATB)

**Comment by juanmam5** [comment] 2018-10-18 09:17
Do you mean I should by Asus TinkerBoard to have my mirror working properly? Which HW do you recommend my to by? Can I install the same software on it?

**Comment by gljones2001** [comment] 2018-10-20 22:12
I have installed this in the home directory, and it did not install to MMM-Hotword in the MagicMirror modules directory. Im now running the commands for install in the modules directory. Is that how its supposed to work?

**Comment by gljones2001** [comment] 2018-10-20 22:13
It also says when building "npm WARN MMM-Hotword@1.0.0 No repository field." What does this mean?

**Comment by eouia** [comment] 2018-10-22 06:53
@gljones2001 
1) You can run MMM-AssistantMk2 directly without MMM-Hotword(hotword detection) by click the MIC icon(color will be changed) then say anything.
2) `npm WARN MMM-Hotword@1.0.0 No repository field.` is nothing to mean. You can ignore.

**Comment by eouia** [comment] 2018-10-22 07:34
@gljones2001 
1) If you are saying about `MMM-AssistantMk2`, that could be executable without `MMM-Hotword`, but hotword detection is not enabled. You can activate MMM-AssistantMk2 by clicking MIC icon then say.
2) `npm WARN MMM-Hotword@1.0.0 No repository field.` is nothing. Ignore that.

**Comment by gljones2001** [comment] 2018-10-22 20:47
I want MMM-AssistantMk2 to run with hotword. I'm not going to have a touchscreen or mouse on it. My display is the lcd panel from a screen taped to a window. I wanted to be able to ask the assistant to just do stuff no problem.

**Comment by gljones2001** [comment] 2018-10-22 20:48
Also, when i use MMM-Assistant with the mic button, it sits there and then says "CONVERSATION ERROR" What is it doing?

**Comment by eouia** [comment] 2018-10-23 06:27
@gljones2001 
1) MMM-AssistantMk2 is able to be run with MMM-Hotword (and additionally MMM-NotificationTrigger also)
2) Usually CONVERSATION ERROR has many reason, but I suspect you might have wrong configuration of audio.

**Comment by sardinax** [comment] 2018-11-02 22:34
> I followed all steps to this point. All has worked pout well, but after adding the Hotword, notification trigger and mk2 assistant to the config.json i get a black blank screen and no working functions. If I remove the modules form th config file i am able toview the basic magic mirror clock, calendar, weather, ect..
> What can i do to remedy this?

Hi,
I have the same issue. How can I solve it?

I have this verbose: 
10 error path /home/pi/MagicMirror/modules/package.json
11 error code ENOENT
12 error errno -2
13 error syscall open
14 error enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
15 error enoent This is related to npm not being able to find a file.

**Comment by eouia** [comment] 2018-11-04 10:55
@sardinax 
Weird message. I think you'd command `npm install` on wrong directory(maybe `~/MagicMirror/modules`). It should be executed on `~/MagicMirror/modules/TARGET_MODULE_DIRECTORY`.

**Comment by eouia** [comment] 2018-11-07 16:30
I'll close this issue. most of problem will be solved with new updates.

**Closed by eouia** 2018-11-07 16:30 UTC

**Comment by Rasptronout** [comment] 2019-09-19 18:42
hey eouia thanks for the project i love it.. but can you help me to show how to change command hide/show modules to screen off/on ? cause ive been confuse when i ask to hide modules assistant say different (height models) please

**Comment by eouia** [comment] 2019-09-19 18:46
That was just why Assistant understood your pronunciation as "Height models" instead of "Hide Modules". Assistant thought "Height models" is most likely what you probably said by your pronunciation and intonation.
