### ISSUE TITLE
So close but can't figure it out. Attempt to free invalid pointer

### ISSUE THREAD

**Issue by cr4zy5pacec0w80y** [eouia/MMM-Hotword#9] opened 2018-10-01 16:36 UTC
I've gotten everything to work except this hotword module. Again I'm on ubuntu 18, so it may be an ubuntu package or lack of an unknown dependency, but I keep getting 
"../../third_party/tcmalloc/chromium/srs/tcmalloc.cc:289] Attempt to free invalid pointer 0x7fffd43e1ba0"

then magic mirror just crashes. 

Not sure why magic mirror (or this module) is trying to use chromium... I've reinstalled bot the notification and hotword modules, rebuilt for electron (Just followed all of your suggestions) but no luck. I am pretty sure it is the hotword module and not the notification module because when I comment out hotword in the config.js it does not crash.

Also during install i'm getting something about needing hoek@4.x or higher, so I attempted to update that but it didn't help.

I'll attach my configurations in a moment, maybe it's a simple mistake.

Do you have any suggestions?

**Comment by cr4zy5pacec0w80y** [comment] 2018-10-01 16:37
my config.js:

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "0.0.0.0", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],
	//zoom: 1.0,
	language: "en",
	timeFormat: 12,
	units: "imperial",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "Weather",
				locationID: "4658590",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "Weather",
				locationID: "4658590",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
/*		{
		    module: "MMM-GoogleAssistant",
		    position: "top_right",
		    config: {
		        maxWidth: "100%",
		        header: "",
		    publishKey: 'pub-c-##########',
		    subscribeKey: 'sub-c-#########',
		    updateDelay: 500
		    }
		},
*/
{
      module: "MMM-AssistantMk2",
      position: "top_left",
      config: {}
},
{
      module: "MMM-NotificationTrigger",
      config: {
        triggers:[
          {
            trigger: "HOTWORD_DETECTED",
            fires: [
              {
                fire:"HOTWORD_PAUSE",

              },
              {
                fire:"ASSISTANT_ACTIVATE",
		delay: 200,
                payload: function(payload) {
                  return {
                    "profile": payload.hotword
                  }
                }
              },
            ]
          },
          {
            trigger: "ASSISTANT_DEACTIVATED",
            fires: [
              {
                fire:"HOTWORD_RESUME"
              }
            ]
          },
        ]
      }
},
{
      module: "MMM-Hotword",
      config: {}
},

		
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by cr4zy5pacec0w80y** [comment] 2018-10-01 16:40
my assistantmk2.js:

//
// Module : MMM-Hotword
//


Module.register("MMM-AssistantMk2", {

	defaults: {
		deviceModelId: "assistan################r", // It should be described in your config.json
		deviceInstanceId: "2AFE4###############", // It should be described in your config.json
		deviceLocation: { // (optional)
			coordinates: { // set the latitude and longitude of the device (rf. mygeoposition.com)
				latitude: 36.201243, // -90.0 - +90.0
				longitude: -86.249616, // -180.0 - +180.0
			},
		},
		useScreen: true,  // set this to true if you want to output results to a screen
		//useWeb: true, // set this to true if you want to see the referenced webpage in mirror. (Reserved for next update)
		//showed contents will be hidden when new conversation starts or interface.stopContentNotification is comming.
		screenZoom: "80%",
		transcriptionHook: {
			//"SCREEN_OFF" : "screen off",
			//"SCREEN_ON" : "screen on",
			//"REBOOT" : "reboot",
			//"SHUTDOWN" : "shut down",
			//"TEST" : "test"
		},
		youtube: {
			use:true,
			height: "480",
			width: "854",
			notifyPlaying: false, // tell other modules whether youtube is playing or not.
		},
		auth: {
			keyFilePath: "./credentials.json"
		},
		audio: {
			encodingIn: "LINEAR16", // supported are LINEAR16 / FLAC (defaults to LINEAR16)
			sampleRateIn: 16000, // supported rates are between 16000-24000 (defaults to 16000)
			encodingOut: "LINEAR16", // supported are LINEAR16 / MP3 / OPUS_IN_OGG (defaults to LINEAR16)
			sampleRateOut: 24000, // supported are 16000 / 24000 (defaults to 24000)
		},
		defaultProfile: "default",
		profiles: {
			"default" : {
				profileFile: "default.json",
				lang: "en-US"
				//currently available (estimation, not all tested):
				//  de-DE, en-AU, en-CA, en-GB, en-US, en-IN
				// fr-CA, fr-FR, it-IT, ja-JP, es-ES, es-MX, ko-KR, pt-BR
				// https://developers.google.com/assistant/sdk/reference/rpc/languages
			},

			//"kids" : {
			//	profileFile: "jarvis.json",
			//	lang: "de-DE"
			//},
			//"myself_korean" : {
			//	profileFile: "default.json",
			//	lang: "ko-KR"
			//}
		},
		record: {
			sampleRate    : 16000,      // audio sample rate
			threshold     : 0.5,        // silence threshold (rec only)
			thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
			thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
			silence       : 1.0,        // seconds of silence before ending
			verbose       : false,      // log info to the console
			recordProgram : "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
			device        : null        // recording device (e.g.: "plughw:1")
		},
	},

	getStyles: function () {
		return ["MMM-AssistantMk2.css"]
	},

	start: function () {
		this.isInitialized = 0
		this.config = this.configAssignment({}, this.defaults, this.config)
		this.sendSocketNotification("INIT", this.config)
		this.headerContent = ""
		this.screenContent = null
		this.ytp = null
		this.videoPlaying = false
		console.log("start")
	},

	getDom : function() {
		var wrapper = document.createElement("div")
		wrapper.className = "sleeping"
		wrapper.id = "ASSISTANT"
		wrapper.onclick = ()=> {
			if (wrapper.className == "sleeping") {
				this.sendSocketNotification("START", this.config.profiles[this.config.defaultProfile])
			}
		}
		var micImg = document.createElement("div")


		micImg.id = "ASSISTANT_MIC"
		var message = document.createElement("div")
		message.id = "ASSISTANT_MESSAGE"
		wrapper.appendChild(micImg)
		wrapper.appendChild(message)
		return wrapper
	},

	prepareScreen: function() {
		var web = document.createElement("iframe")
		web.id = "ASSISTANT_WEB"
		document.body.appendChild(web)
		var screen = document.createElement("iframe")
		screen.id = "ASSISTANT_SCREEN"
		document.body.appendChild(screen)
		var video = document.createElement("div")
		video.id = "ASSISTANT_VIDEO"
		var videoWrapper = document.createElement("div")
		videoWrapper.id = "ASSISTANT_VIDEO_WRAPPER"
		videoWrapper.appendChild(video)
		var videoError = document.createElement("div")
		videoError.id = "ASSISTANT_VIDEO_ERROR"
		videoWrapper.appendChild(videoError)
		document.body.appendChild(videoWrapper)


		var tag = document.createElement("script")
		tag.src = "https://www.youtube.com/iframe_api"
		var firstScriptTag = document.getElementsByTagName("script")[0]
		firstScriptTag.parentNode.insertBefore(tag, firstScriptTag)

		var self = this
		window.onYouTubeIframeAPIReady = () => {
			self.ytp = new YT.Player("ASSISTANT_VIDEO", {
				height: this.config.youtube.height,
				width: this.config.youtube.height,
				playerVars: {
					"autoplay": 1,
					"controls": 0,
					"loop": 1,
					"rel": 0,
				},
				events: {
					"onReady": (event)=>{
						event.target.playVideo()
					},
					"onStateChange": (event)=>{
						if (event.data == 0) {
							setTimeout(()=>{
								self.hideVideo()
							}, 1000)

						}
					},
					"onError": (event)=> {
						console.log("youtube error:", event.data)
						var er = document.getElementById("ASSISTANT_VIDEO_ERROR")
						er.innerHTML = "Youtube error: " + event.data
						setTimeout(()=>{
							self.hideVideo()
						}, 5000)
					}
				}
			})
		}
	},

	showContent: function(url) {
		var screen = document.getElementById("ASSISTANT_WEB")
		screen.src = url
		setTimeout(()=>{
			screen.className = "show"
		},500)
	},

	hideContent: function() {
		var screen = document.getElementById("ASSISTANT_WEB")
		screen.className = "hide"
	},

	showScreen: function() {
		var screen = document.getElementById("ASSISTANT_SCREEN")
		screen.src = this.data.path + "/temp_screen.html"
		setTimeout(()=>{
			screen.className = "show"
		},500)

	},

	hideScreen: function() {
		var screen = document.getElementById("ASSISTANT_SCREEN")
		screen.className = "hide"
	},

	showVideo: function(id, type="video") {
		if (type == "video") {
			this.ytp.loadVideoById(id, 0, "default")
		} else {
			this.ytp.loadPlaylist({
				"list":id,
				"listType":"playlist",
				"index":0
			})
		}
		if (this.config.youtube.notifyPlaying == true) {
			this.videoPlaying = true
			this.sendNotification("ASSISTANT_VIDEO_PLAYING")
		}
		this.ytp.playVideo()
		var wrapper = document.getElementById("ASSISTANT_VIDEO_WRAPPER")
		wrapper.className = "show"
	},

	hideVideo: function() {
		var wrapper = document.getElementById("ASSISTANT_VIDEO_WRAPPER")
		var er = document.getElementById("ASSISTANT_VIDEO_ERROR")
		er.innerHTML = ""
		this.ytp.stopVideo()
		if (this.config.youtube.notifyPlaying == true && this.videoPlaying) {
			this.sendNotification("ASSISTANT_VIDEO_STOP")
			this.videoPlaying = false
		}
		wrapper.className = "hide"
	},



	displayStatus: function(mode, text) {
		var wrapper = document.getElementById("ASSISTANT")
		wrapper.className = mode
		var message = document.getElementById("ASSISTANT_MESSAGE")
		message.innerHTML = text
	},

	notificationReceived: function (notification, payload, sender) {
		switch(notification) {
		case "ALL_MODULES_STARTED":
			//do nothing
			break
		case "DOM_OBJECTS_CREATED":
			this.prepareScreen()
			break
		case "ASSISTANT_ACTIVATE":
			var profileKey = ""
			var profile = {}
			if (payload.profile in this.config.profiles) {
				profileKey = payload.profile
			} else {
				profileKey = this.config.defaultProfile
			}
			profile = this.config.profiles[profileKey]
			this.sendSocketNotification("START", profile)
			break
		case "ASSISTANT_CLEAR":
			this.hideScreen()
			this.hideVideo()
			this.hideContent()
			break
		}
	},


	socketNotificationReceived: function (notification, payload) {
		switch(notification) {
		case "INITIALIZED":
			//do nothing
			break

		case "STARTED":
			this.displayStatus("waiting", "")
			this.hideVideo()
			this.hideContent()
			this.hideScreen()
			break
		case "TRANSCRIPTION":
			if(payload.done == true) {
				this.displayStatus("understanding", payload.transcription)
			} else {
				this.displayStatus("listening", payload.transcription)
			}
			break
		case "TURN_OVER":
			if (payload.error !== null) {
				console.log("TURN_OVER_ERROR:", payload.error)
				this.displayStatu("error", "ERROR")
			} else {
				if (payload.foundHook) {
					console.log ("Hook:", payload.foundHook)
					for(i in payload.foundHook) {
						var hook = payload.foundHook[i]
						this.sendNotification("ASSISTANT_HOOK", {"hook":hook})
					}
				}
				if (payload.foundVideo) {
					console.log ("Video:", payload.foundVideo)
					setTimeout(()=>{
						this.hideScreen()
						this.hideContent()
						this.showVideo(payload.foundVideo, "video")
					}, 1500)
				}
				if (payload.foundVideoList) {
					console.log ("Video Playlist:", payload.foundVideoList)
					setTimeout(()=>{
						this.hideScreen()
						this.hideContent()
						this.showVideo(payload.foundVideoList, "playlist")
					}, 1500)
				}
				if (payload.foundAction) {
					console.log ("Action", payload.foundAction)
					if (payload.foundAction.command !== "action.devices.commands.EXCEPTION") {
						this.sendNotification("ASSISTANT_ACTION", payload.foundAction)
					} else {
						var status = JSON.parse(payload.foundAction.params.status)
						this.displayStatus("error", status.description)
					}
				}
				if (payload.foundWeb) {
					setTimeout(()=>{
						this.hideScreen()
						this.hideVideo()
						this.showContent(payload.foundContent)
					}, 1500)
				}
				if (payload.continue != true) {
					setTimeout(()=>{
						this.displayStatus("sleeping", "")
						this.sendNotification("ASSISTANT_DEACTIVATED", null)
					}, 1000)
				}
			}
			break
		case "SCREEN":
			this.showScreen()
			break
		case "CONVERSATION_ERROR":
			this.displayStatus("error", "CONVERSATION ERROR")
			setTimeout(()=>{
				this.displayStatus("sleeping", "")
				this.sendNotification("ASSISTANT_DEACTIVATED", null)
			}, 3000)
			break
		case "SPEAKING_START":
			break
		case "SPEAKING_END":
			break
		case "CONTINUOUS_TURN":
			break
		case "ASSISTANT_READY":
			break
		case "ASSISTANT_ERROR":
			this.displayStatus("error", "CONVERSATION ERROR")
			setTimeout(()=>{
				this.displayStatus("sleeping", "")
				this.sendNotification("ASSISTANT_DEACTIVATED", null)
			}, 3000)
			break
		case "AUDIO_ERROR": //this is not your fault... sometimes google assistant lost her voice.. Even google staffs can't help this currently.
			this.displayStatus("error", "AUDIO OUT ERROR")
			setTimeout(()=>{
				this.displayStatus("sleeping", "")
				this.sendNotification("ASSISTANT_DEACTIVATED", null)
			}, 3000)
			break
		}
	},

	configAssignment : function (result) {
		var stack = Array.prototype.slice.call(arguments, 1);
		var item;
		var key;
		while (stack.length) {
			item = stack.shift();
			for (key in item) {
				if (item.hasOwnProperty(key)) {
					if (
						typeof result[key] === "object"
						&& result[key]
						&& Object.prototype.toString.call(result[key]) !== "[object Array]"
					) {
						if (typeof item[key] === "object" && item[key] !== null) {
							result[key] = this.configAssignment({}, result[key], item[key]);
						} else {
							result[key] = item[key];
						}
					} else {
						result[key] = item[key];
					}
				}
			}
		}
		return result;
	}
})

**Comment by cr4zy5pacec0w80y** [comment] 2018-10-01 16:41
my notification trigger .js:

//
// Module : MMM-NotificationTrigger
//


Module.register("MMM-NotificationTrigger", {
	defaults: {
		useWebhook: false,
		triggers:[
			{
				trigger: "SAMPLE_INCOMINIG_NOTIFICATION",
				triggerSenderFilter: (sender) => {
					return true
				},
				triggerPayloadFilter: (payload) => {
					return true
				},
				fires: [
					{
						fire:"SAMPLE_OUTGOING_NOTIFICATION",
						payload: (payload) => {
							return payload
						},
						delay: 0,
					},
				],
			},
		]
	},

	start: function() {
		this.sendSocketNotification("INIT")
	},

	socketNotificationReceived: function(notification, payload) {
		if (notification == "WEBHOOK" && this.config.useWebhook) {
			this.notificationReceived(payload.notification, payload.payload, payload.sender)
		}
	},

	notificationReceived: function (notification, payload, sender) {
		var triggers = this.config.triggers
		for(i in triggers) {
			var trigger = triggers[i]
			if (notification == trigger.trigger) {
				var senderFilter = (trigger.triggerSenderFilter)
					? trigger.triggerSenderFilter
					: this.defaults.triggers[0].triggerSenderFilter
				var payloadFilter = (trigger.triggerPayloadFilter)
					? trigger.triggerPayloadFilter
					: this.defaults.triggers[0].triggerPayloadFilter
				if (senderFilter(sender) && payloadFilter(payload)) {
					for(j in trigger.fires) {
						var fire = trigger.fires[j]
						var payloadResult = (fire.payload)
							? fire.payload
							: this.defaults.triggers[0].fires[0].payload
						var result = payloadResult(payload)
						if(fire.delay) {
							setTimeout(()=>{
								this.sendNotification(fire.fire, result)
							}, fire.delay)
						} else {
							this.sendNotification(fire.fire, result)
						}
					}
				}
			}
		}
	},
})

**Comment by cr4zy5pacec0w80y** [comment] 2018-10-01 16:42
and finally my hotword.js:

//
// Module : MMM-Hotword
//


Module.register("MMM-Hotword", {
	defaults: {
		snowboy: [
			{
				hotwords: "smartmirror", //this will be sended to other module for distinguishing which hotword is detected.
				file: "resources/models/smart_mirror.umdl",
				sensitivity: '0.5',
			},
			{
				hotwords: "snowboy",
				file: "resources/models/snowboy.umdl",
				sensitivity: '0.5',
			},
			{
				file: 'resources/models/jarvis.umdl',
				sensitivity: '0.8,0.80',
				hotwords: ['jarvis','jarvis'] //Kitt.ai changed their Jarvis UMDL, it has 2 models in one file. So weird.
				//anyway, you can give different name for each. ['jarvis_1', 'jarvis_2']. Even though I think this is useless.
			}
		],
		record: {
			sampleRate    : 16000,      // audio sample rate
			threshold     : 0.5,        // silence threshold (rec only)
			thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
			thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
			silence       : 1.0,        // seconds of silence before ending
			verbose       : false,      // log info to the console
			recordProgram : 'arecord',  // Defaults to 'arecord' - also supports 'rec' and 'sox'
			device        : null        // recording device (e.g.: 'plughw:1')

		},
		autostart: true,
		autorestart: false,
	},

	notificationReceived: function (notification, payload, sender) {
		switch(notification) {
			case 'ALL_MODULES_STARTED':
				if(this.config.autostart == true) {
					this.sendSocketNotification('RESUME')
				}
				break
			case 'HOTWORD_RESUME':
				this.sendSocketNotification('RESUME')
				break
			case 'HOTWORD_PAUSE':
				this.sendSocketNotification('PAUSE')
				break
		}
	},

	socketNotificationReceived: function (notification, payload) {
		switch(notification) {
			case 'INITIALIZED':
				//do nothing
				break
			case 'NOT_PAUSED':
				this.sendNotification('HOTWORD_LISTENING')
				break
			case 'NOT_RESUMED':
				this.sendNotification('HOTWORD_SLEEPING')
				break
			case 'RESUMED':
				this.sendNotification('HOTWORD_LISTENING')
				break
			case 'PAUSED':
				this.sendNotification('HOTWORD_SLEEPING')
				break
			case 'DETECTED':
				this.sendNotification('HOTWORD_DETECTED', payload)
				break
			case 'ERROR':
				this.sendNotification('HOTWORD_ERROR', payload)
				console.log('[HOTWORD] Error: ', payload)
				break
		}
	},

	start: function () {
		this.isInitialized = 0
		this.config = this.configAssignment({}, this.defaults, this.config)
		this.sendSocketNotification('INIT', this.config)
	},

	configAssignment : function (result) {
		var stack = Array.prototype.slice.call(arguments, 1);
		var item;
		var key;
		while (stack.length) {
			item = stack.shift();
			for (key in item) {
				if (item.hasOwnProperty(key)) {
					if (
						typeof result[key] === 'object'
						&& result[key]
						&& Object.prototype.toString.call(result[key]) !== '[object Array]'
					) {
						if (typeof item[key] === 'object' && item[key] !== null) {
							result[key] = this.configAssignment({}, result[key], item[key]);
						} else {
							result[key] = item[key];
						}
					} else {
						result[key] = item[key];
					}
				}
			}
		}
		return result;
	},
})

**Comment by eouia** [comment] 2018-10-02 06:58
First, I think you should check module one-by-one. I suspect MMM-Hotword has some problems on installment step.
MMM-Hotword is using SNOWBOY, and it is somehow difficult to install.
Read this carefully.
https://github.com/Kitt-AI/snowboy#readme

After some researching, I think I've found something. Latest snowboy isn't compatible with Ubuntu 16.04. Downgrading snowboy to 1.2.0 could be a solution. (My module is using snowboy 1.3.1)
https://github.com/Kitt-AI/snowboy/issues/441

**Comment by eouia** [comment] 2018-10-09 13:13
I'll close this.

**Closed by eouia** 2018-10-09 13:13 UTC

**Comment by Chello** [comment] 2018-12-09 21:41
> First, I think you should check module one-by-one. I suspect MMM-Hotword has some problems on installment step.
> MMM-Hotword is using SNOWBOY, and it is somehow difficult to install.
> Read this carefully.
> https://github.com/Kitt-AI/snowboy#readme
> 
> After some researching, I think I've found something. Latest snowboy seems not to be compatible with Ubuntu 16.04. Downgrading snowboy to 1.2.0 could be a solution. (My module is using snowboy 1.3.1)
> [Kitt-AI/snowboy#441](https://github.com/Kitt-AI/snowboy/issues/441)

Hi.
I'm experiencing a similar issue while running on serveronly. When pointing browser i experienced ``` munmap_chunk() invalid pointer ``` from snowboy
I've done what you say, using snowboy@1.2.0, but more errors appeared like ``` ERROR (ExpectToken():snowboy-io.cc:166) Expected token "<KwInfo>", got instead "<LicenseStart>" ```.
(refer to https://github.com/Kitt-AI/snowboy/issues/241 )

Now I ask, could be possible that my problem is because my OS/node versions?
I tried to install via Virtualbox in a Ubuntu 18.04.1 (node v8.10) and now I'm trying in a Docker container, Debian Stretch and Node 8.11.3. Same problem?

Any suggestions appreciated. Where to search the problem in code?
Thanks everyone in advice.

**Comment by eouia** [comment] 2018-12-10 12:57
I think so. Your environment is not tested by myself (I have no ubuntu machine). Anyway, issues on snowboy of github says your problem might be related with your Ubuntu. I think Debian Stretch could work, But manual compile might be needed, I'm not sure about it.

**Comment by Chello** [comment] 2018-12-10 18:44
Don't exactly know, I'll try again and I will provide feedback. 
I also done several manual compiles in my Debian Stretch on Docker environment (I really think that the problem is not that I'm running it on a Docker container, everything else I tried in general and in particular with MM, worked correctly under containers), but I will retry.
A simple suggestion: which version of Node you suggest to use? 
Again, thanks in advice.

**Comment by eouia** [comment] 2018-12-10 18:52
above node 10.13, there could be compatibility issue for vanilla RPI. It seems some dependencies are missed. You need to compile by manual with some essential dependencies. However, it can be done on RPI, but I'm not sure on Ubuntu.
Snowboy team says these systems are supported currently.
```
Currently Snowboy supports (look into the lib folder):

all versions of Raspberry Pi (with Raspbian based on Debian Jessie 8.0)
64bit Mac OS X
64bit Ubuntu 14.04
iOS
Android
ARM64 (aarch64, Ubuntu 16.04)
```

**Comment by TheStigh** [comment] 2019-01-14 00:54
Hi euoia, I got the same problem running amd64 - Debian Stretch 9.6:

../../third_party/tcmalloc/chromium/src/tcmalloc.cc:289] Attempt to free invalid pointer 0x7ffeaef7b090

Installs didnt give me any errors...?

Any good ideas?

**Comment by eouia** [comment] 2019-01-14 07:13
I think snowboy is not supported Debian on x86.
Snowboy team officially says these platforms are supported.
```
Currently Snowboy supports (look into the lib folder):

all versions of Raspberry Pi (with Raspbian based on Debian Jessie 8.0)
64bit Mac OS X
64bit Ubuntu 14.04
iOS
Android
ARM64 (aarch64, Ubuntu 16.04)
```
